export const ERROR_CODES = {
  INVALID_INPUT: "INVALID_INPUT",
  GITHUB_AUTH_FAILED: "GITHUB_AUTH_FAILED",
  GITHUB_FETCH_FAILED: "GITHUB_FETCH_FAILED",
  KUBERNETES_ERROR: "KUBERNETES_ERROR",
  KUBERNETES_NOT_FOUND: "KUBERNETES_NOT_FOUND",
  KUBERNETES_CONFLICT: "KUBERNETES_CONFLICT",
  NOT_FOUND: "NOT_FOUND",
  YAML_INVALID: "YAML_INVALID",
};
